export const zonesConfig = {
  body: {
    scale: 1,
    zones: [
      {
        id: "head",
        color: 0xff0000,
        height: 0.15,
        width: 0.2,
        depth: 0.75,
        anchor: "top",
      },
      {
        id: "chest",
        color: 0x0000ff,
        height: 0.15,
        width: 0.45,
        depth: 0.2,
        anchor: "below:head",
        gap: 0.015,
        offset: [0, 0, 0.1],
      },
      {
        id: "abdomen",
        color: 0xffff00,
        height: 0.1,
        width: 0.45,
        depth: 0.25,
        anchor: "below:chest",
        gap: 0.015,
        offset: [0, 0, 0.1],
      },
      {
        id: "pelvis",
        color: 0x00ff00,
        height: 0.1,
        width: 0.45,
        depth: 0.3,
        anchor: "below:abdomen",
        gap: 0.015,
        offset: [0, 0, 0.1],
      },
      {
        id: "legs",
        color: 0xff00ff,
        height: 0.4,
        width: 0.15,
        depth: 0.65,
        anchor: "below:pelvis",
        gap: 0.015,
        type: "double",
        xOffset: 0.15,
      },
      {
        id: "back",
        color: 0x00ffff,
        anchor: "between:chest:pelvis",
        width: 0.45,
        depth: 0.2,
        offset: [0, 0, -0.15],
      },
      {
        id: "arms",
        color: 0xffa500,
        height: 0.4,
        width: 0.1,
        depth: 0.25,
        anchor: "chest",
        type: "double",
        xOffset: 0.35,
        rotation: 0.25,
        yOffset: -0.2,
      },
    ],
  },

  skeleton: {
    scale: 0.35,
    yOffsetGlobal: 0,
    zones: [
      {
        id: "skull",
        color: 0xff0000,
        height: 0.05,
        width: 0.12,
        depth: 0.12,
        anchor: "top",
        offset: [0, -0.74, 0],
      },
      {
        id: "ribcage",
        color: 0x0000ff,
        height: 0.05,
        width: 0.25,
        depth: 0.2,
        anchor: "below:skull",
        gap: 0.005,
        offset: [0, -0.74, 0],
      },
      {
        id: "spine",
        color: 0x00ff00,
        height: 0.12,
        width: 0.08,
        depth: 0.12,
        anchor: "below:ribcage",
        gap: 0.005,
        offset: [0, -0.69, 0],
      },
      {
        id: "pelvis",
        color: 0xffff00,
        height: 0.04,
        width: 0.2,
        depth: 0.15,
        anchor: "below:spine",
        gap: 0.005,
        offset: [0, -0.65, 0],
      },
      {
        id: "arms",
        color: 0xffa500,
        height: 0.15,
        width: 0.04,
        depth: 0.05,
        anchor: "ribcage",
        type: "double",
        xOffset: 0.05,
        rotation: 0,
        offset: [0, 0.16, 0],
      },
      {
        id: "legs",
        color: 0xff00ff,
        height: 0.2,
        width: 0.1,
        depth: 0.15,
        anchor: "below:pelvis",
        gap: 0.005,
        type: "double",
        xOffset: 0.03,
        rotation: 0,
        offset: [0, -0.65, 0],
      },
    ],
  },

  brain: {
    scale: 0.5,
    yOffsetGlobal: 0,
    zones: [
      {
        id: "brain",
        color: 0xff6347,
        width: 2.0,
        height: 2.0,
        depth: 2.5,
        anchor: "top",
        offset: [0, 0, 0],
      },
    ],
  },

  respiratory: {
    scale: 0.1,
    zones: [
      {
        id: "larynx",
        color: 0xff6347,
        width: 0.1,
        height: 0.08,
        depth: 0.2,
        anchor: "top",
        offset: [0, -0.95, 0],
      },
      {
        id: "trachea",
        color: 0x1e90ff,
        width: 0.1,
        height: 0.15,
        depth: 0.2,
        anchor: "below:larynx",
        offset: [0, -0.95, 0],
      },
      {
        id: "lungs",
        color: 0x32cd32,
        width: 0.1,
        height: 0.2,
        depth: 0.4,
        type: "double",
        xOffset: 0.01,
        anchor: "below:trachea",
        offset: [0, -0.94, 0],
      },
    ],
  },

  circulatory: {
    scale: 1,
    yOffsetGlobal: 0,
    zones: [
      {
        id: "heart",
        color: 0xff0000,
        width: 0.15,
        height: 0.1,
        depth: 0.2,
        anchor: "top",
        offset: [0.02, 0.4, 0.05],
      },
      {
        id: "headNeck",
        color: 0x0000ff,
        width: 0.25,
        height: 0.15,
        depth: 0.75,
        anchor: "top",
        offset: [0, 0.75, 0],
      },
      {
        id: "abdomen",
        color: 0x9900ff,
        width: 0.3,
        height: 0.2,
        depth: 0.25,
        anchor: "below:heart",
        gap: 0.015,
        offset: [0, 0.45, 0.05],
      },
      {
        id: "legs",
        color: 0x00ff00,
        width: 0.12,
        height: 0.4,
        depth: 0.25,
        anchor: "below:abdomen",
        type: "double",
        xOffset: 0.1,
        offset: [0, 0.45, 0],
      },
      {
        id: "arms",
        color: 0xffa500,
        width: 0.1,
        height: 0.28,
        depth: 0.18,
        anchor: "heart",
        type: "double",
        xOffset: 0.3,
        yOffset: -0.02,
        offset: [0, 1.1, 0],
        rotation: 0.25,
      },
    ],
  },
};
